#!/usr/bin/env bash
set -euo pipefail

# 🔐 Azure Static Web Apps GitHub App Authorization Script
# Fixes: "Build and Deploy Job (pull_request)" failures due to AzureAppServiceCLI permissions

echo "🔐 Azure Static Web Apps Authorization Helper"
echo "=============================================="
echo ""

# Repository info
REPO_OWNER="jgtolentino"
REPO_NAME="pulser"
FULL_REPO="$REPO_OWNER/$REPO_NAME"

echo "📋 Repository: $FULL_REPO"
echo "🎯 Issue: AzureAppServiceCLI GitHub App needs authorization"
echo ""

# Check if gh CLI is available
if ! command -v gh &> /dev/null; then
    echo "❌ GitHub CLI (gh) not found. Please install it first:"
    echo "   brew install gh"
    echo "   # or visit: https://cli.github.com/"
    exit 1
fi

# Check authentication
if ! gh auth status &>/dev/null; then
    echo "🔒 Please authenticate with GitHub CLI first:"
    echo "   gh auth login"
    exit 1
fi

echo "✅ GitHub CLI authenticated"
echo ""

# Display authorization steps
echo "🚀 AUTHORIZATION STEPS:"
echo "======================="
echo ""
echo "1️⃣  **Organization-Level Authorization (Recommended)**"
echo "   👤 Admin access required to tbwa-smp organization"
echo "   🔗 URL: https://github.com/organizations/tbwa-smp/settings/installations"
echo "   📝 Steps:"
echo "      → Find 'AzureAppServiceCLI' in installed apps"
echo "      → Click 'Configure'"
echo "      → Grant access to 'jgtolentino/pulser' repository"
echo "      → Click 'Save'"
echo ""

echo "2️⃣  **Repository-Level Authorization (Alternative)**"
echo "   👤 Repo owner/admin access required"
echo "   🔗 URL: https://github.com/apps/azureappservicecli"
echo "   📝 Steps:"
echo "      → Click 'Configure'"
echo "      → Select 'jgtolentino/pulser' repository"
echo "      → Click 'Install & Authorize'"
echo ""

echo "3️⃣  **Direct Repository Settings**"
echo "   🔗 URL: https://github.com/$FULL_REPO/settings/installations"
echo "   📝 Steps:"
echo "      → Find 'AzureAppServiceCLI'"
echo "      → Click 'Configure'"
echo "      → Ensure permissions are granted"
echo ""

# Auto-open URLs if possible
echo "🌐 Opening authorization URLs..."
echo ""

if command -v open &> /dev/null; then
    echo "📱 Opening GitHub App authorization page..."
    open "https://github.com/apps/azureappservicecli" || true
    sleep 2
    echo "📱 Opening repository settings..."
    open "https://github.com/$FULL_REPO/settings/installations" || true
elif command -v xdg-open &> /dev/null; then
    echo "📱 Opening GitHub App authorization page..."
    xdg-open "https://github.com/apps/azureappservicecli" || true
    sleep 2
    echo "📱 Opening repository settings..."
    xdg-open "https://github.com/$FULL_REPO/settings/installations" || true
else
    echo "🔗 Please manually visit these URLs:"
    echo "   → https://github.com/apps/azureappservicecli"
    echo "   → https://github.com/$FULL_REPO/settings/installations"
fi

echo ""
echo "⏳ After authorization, test the fix:"
echo "======================================"
echo ""

# Generate test command
echo "📋 Test Command:"
echo "   gh pr view 6 --repo $FULL_REPO"
echo "   # Then click 'Re-run all jobs' or close/reopen the PR"
echo ""

echo "🎯 Expected Result:"
echo "   ✅ Build and Deploy Job (pull_request) → SUCCESS"
echo "   ✅ All quality gates pass (tests, guardrails, lighthouse)"
echo "   ✅ Green checkmarks across the entire CI pipeline"
echo ""

echo "🚨 Troubleshooting:"
echo "==================="
echo "If still failing after authorization:"
echo "   1. Wait 2-3 minutes for GitHub to propagate permissions"
echo "   2. Try re-running the workflow again"
echo "   3. Check GitHub Actions logs for different error messages"
echo "   4. Verify the app has 'Actions' and 'Contents' permissions"
echo ""

echo "📞 Contact:"
echo "==========="
echo "   🤖 This script generated by Claude Code"
echo "   📧 For org admin help, contact your GitHub organization admin"
echo "   🔗 GitHub App: https://github.com/apps/azureappservicecli"
echo ""

# Save authorization record
AUTH_LOG="logs/azure_app_authorization_$(date +%Y%m%d_%H%M%S).log"
mkdir -p logs
{
    echo "Azure Static Web Apps GitHub App Authorization"
    echo "=============================================="
    echo "Date: $(date)"
    echo "Repository: $FULL_REPO"
    echo "Issue: AzureAppServiceCLI permissions needed for PR deployments"
    echo "Status: Authorization script executed"
    echo ""
    echo "Required Actions:"
    echo "1. Authorize AzureAppServiceCLI app for repository"
    echo "2. Re-run PR #6 checks"
    echo "3. Verify green CI pipeline"
    echo ""
    echo "URLs for authorization:"
    echo "- App: https://github.com/apps/azureappservicecli"
    echo "- Repo: https://github.com/$FULL_REPO/settings/installations"
    echo ""
} > "$AUTH_LOG"

echo "📝 Authorization log saved: $AUTH_LOG"
echo ""
echo "🎉 Ready to authorize! Follow the steps above to fix the CI/CD pipeline."