#!/bin/bash
# Export Helper for project_scout_with_genai
# Generated by validate_diagram_formats.js on 2025-05-12T17:40:40.843Z

# Ensure directories exist
mkdir -p /Users/tbwa/Documents/GitHub/InsightPulseAI_SKR/tools/js/juicer-stack/docs/images
mkdir -p /Users/tbwa/Documents/GitHub/InsightPulseAI_SKR/tools/js/juicer-stack/docs/images/thumbnails
mkdir -p /Users/tbwa/Documents/GitHub/InsightPulseAI_SKR/tools/js/juicer-stack/docs/images/archive

echo "Export Helper for project_scout_with_genai"
echo "================================="
echo ""

if command -v draw.io &> /dev/null; then
    # Using draw.io CLI
    echo "Using draw.io CLI for exports"
    
    
    # PNG Export
    echo "Generating PNG export..."
    draw.io -x -f png -s 2 -o "/Users/tbwa/Documents/GitHub/InsightPulseAI_SKR/tools/js/juicer-stack/docs/images/project_scout_with_genai.png" "/Users/tbwa/Documents/GitHub/InsightPulseAI_SKR/tools/js/juicer-stack/docs/diagrams/project_scout_with_genai.drawio" && \
        echo "✓ PNG export created: /Users/tbwa/Documents/GitHub/InsightPulseAI_SKR/tools/js/juicer-stack/docs/images/project_scout_with_genai.png" || \
        echo "✗ PNG export failed"
    
    
    
    # SVG Export
    echo "Generating SVG export..."
    draw.io -x -f svg -o "/Users/tbwa/Documents/GitHub/InsightPulseAI_SKR/tools/js/juicer-stack/docs/images/project_scout_with_genai.svg" "/Users/tbwa/Documents/GitHub/InsightPulseAI_SKR/tools/js/juicer-stack/docs/diagrams/project_scout_with_genai.drawio" && \
        echo "✓ SVG export created: /Users/tbwa/Documents/GitHub/InsightPulseAI_SKR/tools/js/juicer-stack/docs/images/project_scout_with_genai.svg" || \
        echo "✗ SVG export failed"
    
    
    
    # Thumbnail
    echo "Generating thumbnail..."
    draw.io -x -f png -s 1 -o "/Users/tbwa/Documents/GitHub/InsightPulseAI_SKR/tools/js/juicer-stack/docs/images/thumbnails/temp.png" "/Users/tbwa/Documents/GitHub/InsightPulseAI_SKR/tools/js/juicer-stack/docs/diagrams/project_scout_with_genai.drawio" && \
        convert "/Users/tbwa/Documents/GitHub/InsightPulseAI_SKR/tools/js/juicer-stack/docs/images/thumbnails/temp.png" -resize 300x "/Users/tbwa/Documents/GitHub/InsightPulseAI_SKR/tools/js/juicer-stack/docs/images/thumbnails/project_scout_with_genai_thumb.png" && \
        rm "/Users/tbwa/Documents/GitHub/InsightPulseAI_SKR/tools/js/juicer-stack/docs/images/thumbnails/temp.png" && \
        echo "✓ Thumbnail created: /Users/tbwa/Documents/GitHub/InsightPulseAI_SKR/tools/js/juicer-stack/docs/images/thumbnails/project_scout_with_genai_thumb.png" || \
        echo "✗ Thumbnail creation failed"
    
    
    # Archive copy
    TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
    cp "/Users/tbwa/Documents/GitHub/InsightPulseAI_SKR/tools/js/juicer-stack/docs/images/project_scout_with_genai.png" "/Users/tbwa/Documents/GitHub/InsightPulseAI_SKR/tools/js/juicer-stack/docs/images/archive/project_scout_with_genai_${TIMESTAMP}.png" && \
        echo "✓ Archive copy created: /Users/tbwa/Documents/GitHub/InsightPulseAI_SKR/tools/js/juicer-stack/docs/images/archive/project_scout_with_genai_${TIMESTAMP}.png"
else
    # Manual instructions
    echo "draw.io CLI not found. Please follow these manual steps:"
    echo ""
    
    
    echo "1. PNG Export:"
    echo "   - Open /Users/tbwa/Documents/GitHub/InsightPulseAI_SKR/tools/js/juicer-stack/docs/diagrams/project_scout_with_genai.drawio in draw.io"
    echo "   - File > Export as > PNG..."
    echo "   - Set scale to 2x"
    echo "   - Save to: /Users/tbwa/Documents/GitHub/InsightPulseAI_SKR/tools/js/juicer-stack/docs/images/project_scout_with_genai.png"
    echo ""
    
    
    
    echo "2. SVG Export:"
    echo "   - Open /Users/tbwa/Documents/GitHub/InsightPulseAI_SKR/tools/js/juicer-stack/docs/diagrams/project_scout_with_genai.drawio in draw.io"
    echo "   - File > Export as > SVG..."
    echo "   - Save to: /Users/tbwa/Documents/GitHub/InsightPulseAI_SKR/tools/js/juicer-stack/docs/images/project_scout_with_genai.svg"
    echo ""
    
    
    
    echo "3. Thumbnail:"
    echo "   - Open /Users/tbwa/Documents/GitHub/InsightPulseAI_SKR/tools/js/juicer-stack/docs/diagrams/project_scout_with_genai.drawio in draw.io"
    echo "   - File > Export as > PNG..."
    echo "   - Set scale to 1x"
    echo "   - Save to: /Users/tbwa/Documents/GitHub/InsightPulseAI_SKR/tools/js/juicer-stack/docs/images/thumbnails/project_scout_with_genai_thumb.png"
    echo "   - Use an image editor to resize to 300px width"
    echo ""
    
    
    echo "4. Archive copy:"
    echo "   - Copy /Users/tbwa/Documents/GitHub/InsightPulseAI_SKR/tools/js/juicer-stack/docs/images/project_scout_with_genai.png to /Users/tbwa/Documents/GitHub/InsightPulseAI_SKR/tools/js/juicer-stack/docs/images/archive/project_scout_with_genai_YYYYMMDD_HHMMSS.png"
    echo "   - Replace YYYYMMDD_HHMMSS with current timestamp"
fi

echo ""
echo "After creating exports, run this script again to validate:"
echo "node validate_diagram_formats.js project_scout_with_genai"
