agent: bruno
model: claude-3-sonnet-20240229
llm_provider: anthropic
memory: true
default_tool: explain
repl_mode: true
max_tokens: 2048
temperature: 0.7

# Tool configurations
tools:
  fix:
    auto_format: true
    preserve_comments: true
  explain:
    detail_level: medium
    include_examples: true
  test:
    coverage_target: 80
    include_edge_cases: true

# Development settings
dev:
  debug: false
  log_level: info
  cache_responses: true