agent: bruno
llm_provider: local
local_model: deepseek-coder:33b-instruct-q4_K_M
ollama_url: http://127.0.0.1:11434
fallback_provider: claude
allow_cloud: false
memory: true
default_tool: explain
repl_mode: true
max_tokens: 2048
temperature: 0.7

# Privacy settings
privacy:
  no_telemetry: true
  no_remote_fetch: true
  local_sessions_only: true

# Tool configurations
tools:
  fix:
    auto_format: true
    preserve_comments: true
  explain:
    detail_level: medium
    include_examples: true
  test:
    coverage_target: 80
    include_edge_cases: true

# Shell sandbox settings
shell:
  enabled: true
  blocked_commands:
    - "rm -rf"
    - "sudo"
    - "curl"
    - "wget"
    - "ssh"
  warn_commands:
    - "rm"
    - "mv"
    - "cp -r"

# Development settings
dev:
  debug: false
  log_level: info
  cache_responses: true
  offline_mode: true